name: Create latex PDF release
on: workflow_dispatch
jobs:
  create_latex_pdf_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          ref: main
          submodules: true
          token: ${{ secrets.MY_REPO_PAT }}
      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date_with_time::$(date +'%Y-%m-%d_%H-%M-%S')"
          echo "::set-output name=date_with_time_escaped::$(date +'%Y-%m-%d\_%H-%M-%S')"
          echo "::set-output name=date_without_time::$(date +'%Y-%m-%d')"
          echo "::set-output name=year::$(date +'%Y')"
      - name: Compile latex document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: oracle-definition.tex
      - name: Rename generated PDF file
        run: mv oracle-definition.pdf oracle-definition_${{ steps.date.outputs.date_without_time }}.pdf
        shell: bash
      - name: Create tag with current date
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.date.outputs.date_without_time }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.date.outputs.date_without_time }}
          artifacts: oracle-definition_${{ steps.date.outputs.date_without_time }}.pdf
          body: |
            :warning: The exported manuscript is not yet officially published.
            
            :books: You may use the following BibTeX entry.
            ```
            @Misc{Hoss${{ steps.date.outputs.year }}oracle,
              author       = {Michael Hoss},
              howpublished = {GitHub preprint},
              note         = {{v${{ steps.date.outputs.date_without_time }}}},
              title        = {Checklist to Define Test Oracles for Identifying {TP, FP, and FN} Objects in Automated Driving},
              year         = {${{ steps.date.outputs.year }}},
              timestamp    = {${{ steps.date.outputs.date_without_time }}},
              url          = {https://github.com/michael-hoss/paper-oracle-definition/releases/v${{ steps.date.outputs.date_without_time }}},
            }
            ```
          token: ${{ secrets.GITHUB_TOKEN }}
